/// Flutter icons Custom
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'Custom';
  static const String _kFontPkg = null;

  static const IconData badge = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData businessman = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData found = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qr_code = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reading_book = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_bag = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
